"""update some model fields

Revision ID: 174df40cf3ff
Revises: b23f6c33668d
Create Date: 2024-11-14 11:47:28.186898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174df40cf3ff'
down_revision: Union[str, None] = 'b23f6c33668d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'messages', ['id'])
    op.drop_constraint('messages_room_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'room_members', ['id'])
    op.drop_constraint('room_members_room_id_fkey', 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'rooms', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key('room_members_room_id_fkey', 'room_members', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'room_members', type_='unique')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_room_id_fkey', 'messages', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='unique')
    op.alter_column('messages', 'room_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
